language: php
sudo: false
php:
  - 7.1
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
  - TASK_TESTS=1
  - TASK_TESTS_COVERAGE=0
  - TASK_CS=1
  - TASK_SCA=0
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
install:
- composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
script:
- vendor/bin/phpunit --verbose;
- composer phpstan
- vendor/bin/infection --threads=4
- composer cs-check
after_success:
- vendor/bin/coveralls -v
